export const GET_TODO_TASKS_SUCCESS = 'GET_TODO_TASKS_SUCCESS';
export const GET_TODO_TASKS_ERROR = 'GET_TODO_TASKS_ERROR';
export const GET_DONE_TASKS_SUCCESS = 'GET_DONE_TASKS_SUCCESS';
export const GET_DONE_TASKS_ERROR = 'GET_DONE_TASKS_ERROR';